sonar.organization=pintarparkir
sonar.projectKey=pintarparkir_user-service
sonar.projectName=user-service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.exclusions=\
  **/*_test.go,\
  **/*.pb.go,\
  **/*_grpc.pb.go,\
  **/api/proto/**,\
  **/bin/**,\
  **/data/**,\
  **/docs/**,\
  **/mock/**,\
  **/mocks/**,\
  **/vendor/**

sonar.coverage.exclusions=\
  **/*_test.go,\
  **/api/proto/**,\
  **/cmd/**,\
  **/mock/**,\
  **/mocks/**,\
  **/scripts/**,\
  **/test/**

sonar.cpd.exclusions=\
  **/*.pb.go,\
  **/*_grpc.pb.go,\
  **/api/proto/**,\
  **/mock/**,\
  **/mocks/**,\
  **/handler/grpc/**,\
  **/handler/http/**,\
  **/cmd/**

sonar.go.coverage.reportPaths=coverage.out
