// Code generated by hand to mirror the gomock surface — keeps the build
// running without requiring `go generate` in CI. Replace with `mockgen` output
// once mockgen is installed: `make mocks`.
package repository

import (
	"context"
	"sync"

	"github.com/farid/user-service/internal/user/model"
)

// MockUserRepository is a thread-safe in-memory fake for tests.
type MockUserRepository struct {
	mu       sync.Mutex
	byID     map[string]model.User
	byExtID  map[string]string // external_user_id → id

	CreateFn              func(ctx context.Context, u model.User) (model.User, error)
	GetByIDFn             func(ctx context.Context, id string) (*model.User, error)
	GetByExtIDFn          func(ctx context.Context, extID string) (*model.User, error)
	GetOrCreateByMSISDNFn func(ctx context.Context, msisdn, extID, fullName string) (*model.User, error)
	UpdateFn              func(ctx context.Context, u model.User, ev int) (model.User, error)
	SoftDeleteFn          func(ctx context.Context, id string) error
	ListFn                func(ctx context.Context, req model.ListUsersRequest) ([]model.User, int, error)
}

// NewMockUserRepository returns an empty mock with default in-memory behaviour.
func NewMockUserRepository() *MockUserRepository {
	return &MockUserRepository{byID: map[string]model.User{}, byExtID: map[string]string{}}
}

func (m *MockUserRepository) Create(ctx context.Context, u model.User) (model.User, error) {
	if m.CreateFn != nil {
		return m.CreateFn(ctx, u)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	if u.ID == "" {
		u.ID = "mock-" + u.ExternalUserID
	}
	u.Version = 1
	m.byID[u.ID] = u
	m.byExtID[u.ExternalUserID] = u.ID
	return u, nil
}

func (m *MockUserRepository) GetByID(ctx context.Context, id string) (*model.User, error) {
	if m.GetByIDFn != nil {
		return m.GetByIDFn(ctx, id)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	if u, ok := m.byID[id]; ok {
		return &u, nil
	}
	return nil, notFound()
}

func (m *MockUserRepository) GetOrCreateByMSISDN(ctx context.Context, msisdn, extID, fullName string) (*model.User, error) {
	if m.GetOrCreateByMSISDNFn != nil {
		return m.GetOrCreateByMSISDNFn(ctx, msisdn, extID, fullName)
	}
	// Default: delegate to existing Create/GetByExternalID logic.
	if u, err := m.GetByExternalID(ctx, extID); err == nil {
		return u, nil
	}
	created, err := m.Create(ctx, model.User{
		ExternalUserID: extID, FullName: fullName, PhoneE164: msisdn, Status: model.USER_ACTIVE,
	})
	if err != nil {
		return nil, err
	}
	return &created, nil
}

func (m *MockUserRepository) GetByExternalID(ctx context.Context, extID string) (*model.User, error) {
	if m.GetByExtIDFn != nil {
		return m.GetByExtIDFn(ctx, extID)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	if id, ok := m.byExtID[extID]; ok {
		u := m.byID[id]
		return &u, nil
	}
	return nil, notFound()
}

func (m *MockUserRepository) Update(ctx context.Context, u model.User, ev int) (model.User, error) {
	if m.UpdateFn != nil {
		return m.UpdateFn(ctx, u, ev)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	cur, ok := m.byID[u.ID]
	if !ok {
		return model.User{}, notFound()
	}
	if ev != 0 && cur.Version != ev {
		return model.User{}, conflict()
	}
	if u.FullName != "" {
		cur.FullName = u.FullName
	}
	if u.PhoneE164 != "" {
		cur.PhoneE164 = u.PhoneE164
	}
	if u.Email != "" {
		cur.Email = u.Email
	}
	cur.Version++
	m.byID[u.ID] = cur
	return cur, nil
}

func (m *MockUserRepository) SoftDelete(ctx context.Context, id string) error {
	if m.SoftDeleteFn != nil {
		return m.SoftDeleteFn(ctx, id)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	cur, ok := m.byID[id]
	if !ok {
		return nil // idempotent
	}
	cur.Status = model.USER_DELETED
	m.byID[id] = cur
	return nil
}

func (m *MockUserRepository) List(ctx context.Context, req model.ListUsersRequest) ([]model.User, int, error) {
	if m.ListFn != nil {
		return m.ListFn(ctx, req)
	}
	m.mu.Lock(); defer m.mu.Unlock()
	out := make([]model.User, 0, len(m.byID))
	for _, u := range m.byID {
		if req.StatusFilter != "" {
			// Explicit filter: return only matching status (including DELETED).
			if u.Status != req.StatusFilter {
				continue
			}
		} else {
			// Default: exclude soft-deleted rows.
			if u.Status == model.USER_DELETED {
				continue
			}
		}
		out = append(out, u)
	}
	return out, len(out), nil
}
