// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus controls whether a user can transact.
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 2
	UserStatus_USER_STATUS_DELETED     UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_api_proto_user_v1_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// VehicleType matches the vehicle_type Postgres enum used by the reservation service.
type VehicleType int32

const (
	VehicleType_VEHICLE_TYPE_UNSPECIFIED VehicleType = 0
	VehicleType_VEHICLE_TYPE_CAR         VehicleType = 1
	VehicleType_VEHICLE_TYPE_MOTORCYCLE  VehicleType = 2
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "VEHICLE_TYPE_UNSPECIFIED",
		1: "VEHICLE_TYPE_CAR",
		2: "VEHICLE_TYPE_MOTORCYCLE",
	}
	VehicleType_value = map[string]int32{
		"VEHICLE_TYPE_UNSPECIFIED": 0,
		"VEHICLE_TYPE_CAR":         1,
		"VEHICLE_TYPE_MOTORCYCLE":  2,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_user_v1_user_proto_enumTypes[1].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_api_proto_user_v1_user_proto_enumTypes[1]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{1}
}

// User is the canonical driver profile record. PII fields (phone, email) are
// encrypted at rest by the repository layer.
type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalUserId string                 `protobuf:"bytes,2,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"` // identity from super-app JWT
	FullName       string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneE164      string                 `protobuf:"bytes,4,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"` // MSISDN — used for SMS notification
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status         UserStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=parkirpintar.user.v1.UserStatus" json:"status,omitempty"`
	Version        int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Vehicle is a registered license plate belonging to a driver.
type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Nopol         string                 `protobuf:"bytes,3,opt,name=nopol,proto3" json:"nopol,omitempty"` // e.g. "B1234ABC"
	VehicleType   VehicleType            `protobuf:"varint,4,opt,name=vehicle_type,json=vehicleType,proto3,enum=parkirpintar.user.v1.VehicleType" json:"vehicle_type,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Vehicle) GetNopol() string {
	if x != nil {
		return x.Nopol
	}
	return ""
}

func (x *Vehicle) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *Vehicle) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Vehicle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneE164      string                 `protobuf:"bytes,3,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// UpsertDriverRequest is called by the gateway on every incoming request.
// Creates the driver profile on first contact; returns existing on retry.
type UpsertDriverRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PhoneE164      string                 `protobuf:"bytes,1,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`                  // MSISDN from JWT (required)
	ExternalUserId string                 `protobuf:"bytes,2,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"` // super-app identity (required)
	FullName       string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`                     // optional — updated when provided
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertDriverRequest) Reset() {
	*x = UpsertDriverRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDriverRequest) ProtoMessage() {}

func (x *UpsertDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDriverRequest.ProtoReflect.Descriptor instead.
func (*UpsertDriverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertDriverRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *UpsertDriverRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *UpsertDriverRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByExternalIdRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserByExternalIdRequest) Reset() {
	*x = GetUserByExternalIdRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByExternalIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByExternalIdRequest) ProtoMessage() {}

func (x *GetUserByExternalIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByExternalIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByExternalIdRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByExternalIdRequest) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneE164       string                 `protobuf:"bytes,3,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ExpectedVersion int32                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // optimistic lock
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetExpectedVersion() int32 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // default 50, max 200
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	StatusFilter  UserStatus             `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=parkirpintar.user.v1.UserStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetStatusFilter() UserStatus {
	if x != nil {
		return x.StatusFilter
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RegisterVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Nopol         string                 `protobuf:"bytes,2,opt,name=nopol,proto3" json:"nopol,omitempty"` // e.g. "B 1234 ABC" — normalised server-side
	VehicleType   VehicleType            `protobuf:"varint,3,opt,name=vehicle_type,json=vehicleType,proto3,enum=parkirpintar.user.v1.VehicleType" json:"vehicle_type,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVehicleRequest) Reset() {
	*x = RegisterVehicleRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVehicleRequest) ProtoMessage() {}

func (x *RegisterVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVehicleRequest.ProtoReflect.Descriptor instead.
func (*RegisterVehicleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterVehicleRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RegisterVehicleRequest) GetNopol() string {
	if x != nil {
		return x.Nopol
	}
	return ""
}

func (x *RegisterVehicleRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *RegisterVehicleRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *ListVehiclesRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_api_proto_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

var File_api_proto_user_v1_user_proto protoreflect.FileDescriptor

const file_api_proto_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/user/v1/user.proto\x12\x14parkirpintar.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10external_user_id\x18\x02 \x01(\tR\x0eexternalUserId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x04 \x01(\tR\tphoneE164\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .parkirpintar.user.v1.UserStatusR\x06status\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xec\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x14\n" +
	"\x05nopol\x18\x03 \x01(\tR\x05nopol\x12D\n" +
	"\fvehicle_type\x18\x04 \x01(\x0e2!.parkirpintar.user.v1.VehicleTypeR\vvehicleType\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8f\x01\n" +
	"\x11CreateUserRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x03 \x01(\tR\tphoneE164\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"{\n" +
	"\x13UpsertDriverRequest\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x01 \x01(\tR\tphoneE164\x12(\n" +
	"\x10external_user_id\x18\x02 \x01(\tR\x0eexternalUserId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x1aGetUserByExternalIdRequest\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\"\xa0\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x03 \x01(\tR\tphoneE164\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x05R\x0fexpectedVersion\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x87\x01\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12E\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2 .parkirpintar.user.v1.UserStatusR\fstatusFilter\"[\n" +
	"\x11ListUsersResponse\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.parkirpintar.user.v1.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb0\x01\n" +
	"\x16RegisterVehicleRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x14\n" +
	"\x05nopol\x18\x02 \x01(\tR\x05nopol\x12D\n" +
	"\fvehicle_type\x18\x03 \x01(\x0e2!.parkirpintar.user.v1.VehicleTypeR\vvehicleType\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\"2\n" +
	"\x13ListVehiclesRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"Q\n" +
	"\x14ListVehiclesResponse\x129\n" +
	"\bvehicles\x18\x01 \x03(\v2\x1d.parkirpintar.user.v1.VehicleR\bvehicles*u\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03*^\n" +
	"\vVehicleType\x12\x1c\n" +
	"\x18VEHICLE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VEHICLE_TYPE_CAR\x10\x01\x12\x1b\n" +
	"\x17VEHICLE_TYPE_MOTORCYCLE\x10\x022\xca\x06\n" +
	"\vUserService\x12Q\n" +
	"\n" +
	"CreateUser\x12'.parkirpintar.user.v1.CreateUserRequest\x1a\x1a.parkirpintar.user.v1.User\x12U\n" +
	"\fUpsertDriver\x12).parkirpintar.user.v1.UpsertDriverRequest\x1a\x1a.parkirpintar.user.v1.User\x12S\n" +
	"\vGetUserById\x12(.parkirpintar.user.v1.GetUserByIdRequest\x1a\x1a.parkirpintar.user.v1.User\x12c\n" +
	"\x13GetUserByExternalId\x120.parkirpintar.user.v1.GetUserByExternalIdRequest\x1a\x1a.parkirpintar.user.v1.User\x12Q\n" +
	"\n" +
	"UpdateUser\x12'.parkirpintar.user.v1.UpdateUserRequest\x1a\x1a.parkirpintar.user.v1.User\x12_\n" +
	"\n" +
	"DeleteUser\x12'.parkirpintar.user.v1.DeleteUserRequest\x1a(.parkirpintar.user.v1.DeleteUserResponse\x12\\\n" +
	"\tListUsers\x12&.parkirpintar.user.v1.ListUsersRequest\x1a'.parkirpintar.user.v1.ListUsersResponse\x12^\n" +
	"\x0fRegisterVehicle\x12,.parkirpintar.user.v1.RegisterVehicleRequest\x1a\x1d.parkirpintar.user.v1.Vehicle\x12e\n" +
	"\fListVehicles\x12).parkirpintar.user.v1.ListVehiclesRequest\x1a*.parkirpintar.user.v1.ListVehiclesResponseB8Z6github.com/farid/parkirpintar/api/proto/user/v1;userv1b\x06proto3"

var (
	file_api_proto_user_v1_user_proto_rawDescOnce sync.Once
	file_api_proto_user_v1_user_proto_rawDescData []byte
)

func file_api_proto_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_v1_user_proto_rawDesc), len(file_api_proto_user_v1_user_proto_rawDesc)))
	})
	return file_api_proto_user_v1_user_proto_rawDescData
}

var file_api_proto_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_user_v1_user_proto_goTypes = []any{
	(UserStatus)(0),                    // 0: parkirpintar.user.v1.UserStatus
	(VehicleType)(0),                   // 1: parkirpintar.user.v1.VehicleType
	(*User)(nil),                       // 2: parkirpintar.user.v1.User
	(*Vehicle)(nil),                    // 3: parkirpintar.user.v1.Vehicle
	(*CreateUserRequest)(nil),          // 4: parkirpintar.user.v1.CreateUserRequest
	(*UpsertDriverRequest)(nil),        // 5: parkirpintar.user.v1.UpsertDriverRequest
	(*GetUserByIdRequest)(nil),         // 6: parkirpintar.user.v1.GetUserByIdRequest
	(*GetUserByExternalIdRequest)(nil), // 7: parkirpintar.user.v1.GetUserByExternalIdRequest
	(*UpdateUserRequest)(nil),          // 8: parkirpintar.user.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),          // 9: parkirpintar.user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),         // 10: parkirpintar.user.v1.DeleteUserResponse
	(*ListUsersRequest)(nil),           // 11: parkirpintar.user.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 12: parkirpintar.user.v1.ListUsersResponse
	(*RegisterVehicleRequest)(nil),     // 13: parkirpintar.user.v1.RegisterVehicleRequest
	(*ListVehiclesRequest)(nil),        // 14: parkirpintar.user.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),       // 15: parkirpintar.user.v1.ListVehiclesResponse
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
}
var file_api_proto_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: parkirpintar.user.v1.User.status:type_name -> parkirpintar.user.v1.UserStatus
	16, // 1: parkirpintar.user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: parkirpintar.user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: parkirpintar.user.v1.Vehicle.vehicle_type:type_name -> parkirpintar.user.v1.VehicleType
	16, // 4: parkirpintar.user.v1.Vehicle.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: parkirpintar.user.v1.ListUsersRequest.status_filter:type_name -> parkirpintar.user.v1.UserStatus
	2,  // 6: parkirpintar.user.v1.ListUsersResponse.users:type_name -> parkirpintar.user.v1.User
	1,  // 7: parkirpintar.user.v1.RegisterVehicleRequest.vehicle_type:type_name -> parkirpintar.user.v1.VehicleType
	3,  // 8: parkirpintar.user.v1.ListVehiclesResponse.vehicles:type_name -> parkirpintar.user.v1.Vehicle
	4,  // 9: parkirpintar.user.v1.UserService.CreateUser:input_type -> parkirpintar.user.v1.CreateUserRequest
	5,  // 10: parkirpintar.user.v1.UserService.UpsertDriver:input_type -> parkirpintar.user.v1.UpsertDriverRequest
	6,  // 11: parkirpintar.user.v1.UserService.GetUserById:input_type -> parkirpintar.user.v1.GetUserByIdRequest
	7,  // 12: parkirpintar.user.v1.UserService.GetUserByExternalId:input_type -> parkirpintar.user.v1.GetUserByExternalIdRequest
	8,  // 13: parkirpintar.user.v1.UserService.UpdateUser:input_type -> parkirpintar.user.v1.UpdateUserRequest
	9,  // 14: parkirpintar.user.v1.UserService.DeleteUser:input_type -> parkirpintar.user.v1.DeleteUserRequest
	11, // 15: parkirpintar.user.v1.UserService.ListUsers:input_type -> parkirpintar.user.v1.ListUsersRequest
	13, // 16: parkirpintar.user.v1.UserService.RegisterVehicle:input_type -> parkirpintar.user.v1.RegisterVehicleRequest
	14, // 17: parkirpintar.user.v1.UserService.ListVehicles:input_type -> parkirpintar.user.v1.ListVehiclesRequest
	2,  // 18: parkirpintar.user.v1.UserService.CreateUser:output_type -> parkirpintar.user.v1.User
	2,  // 19: parkirpintar.user.v1.UserService.UpsertDriver:output_type -> parkirpintar.user.v1.User
	2,  // 20: parkirpintar.user.v1.UserService.GetUserById:output_type -> parkirpintar.user.v1.User
	2,  // 21: parkirpintar.user.v1.UserService.GetUserByExternalId:output_type -> parkirpintar.user.v1.User
	2,  // 22: parkirpintar.user.v1.UserService.UpdateUser:output_type -> parkirpintar.user.v1.User
	10, // 23: parkirpintar.user.v1.UserService.DeleteUser:output_type -> parkirpintar.user.v1.DeleteUserResponse
	12, // 24: parkirpintar.user.v1.UserService.ListUsers:output_type -> parkirpintar.user.v1.ListUsersResponse
	3,  // 25: parkirpintar.user.v1.UserService.RegisterVehicle:output_type -> parkirpintar.user.v1.Vehicle
	15, // 26: parkirpintar.user.v1.UserService.ListVehicles:output_type -> parkirpintar.user.v1.ListVehiclesResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_user_v1_user_proto_init() }
func file_api_proto_user_v1_user_proto_init() {
	if File_api_proto_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_v1_user_proto_rawDesc), len(file_api_proto_user_v1_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_v1_user_proto_depIdxs,
		EnumInfos:         file_api_proto_user_v1_user_proto_enumTypes,
		MessageInfos:      file_api_proto_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_v1_user_proto = out.File
	file_api_proto_user_v1_user_proto_goTypes = nil
	file_api_proto_user_v1_user_proto_depIdxs = nil
}
